export const orderType = ["Purchase", "Trade", "Group Order", "Other"];

export const sellerPlatform = [
  "Instagram",
  "Twitter",
  "eBay",
  "Mercari",
  "Depop",
  "Whatsapp",
  "Website",
  "Proxy",
  "Other",
];

export const itemType = [
  "Photocard",
  "Postcard",
  "4x6",
  "Printed Photo",
  "A4",
  "Album",
  "Lightstick",
  "Concert",
  "Season's Greetings",
  "Fanclub",
  "Misc.",
];

export const orderStatus = [
  "Order Placed",
  "Waiting for Shipment",
  "Waiting for Pre-Order Release",
  "Waiting for Seller to Receive",
  "Waiting for GOM to Receive",
  "Waiting for Proxy to Ship",
  "Waiting for GOM to Ship",
  "Waiting for K Address to Ship",
  "Waiting for J Address to Ship",
  "Waiting for C Address to Ship",
  "Waiting for USA Address to Ship",
  "Seller On Hitaus",
  "Shipped",
  "Shipped to Seller",
  "Shipped to GOM",
  "Shipped to Proxy",
  "Shipped to K Address",
  "Shipped to J Address",
  "Shipped to C Address",
  "Shipped to USA Address",
  "In Customs",
  "Arrived",
  "Arrived to Proxy",
  "Arrived at K Address",
  "Arrived at J Address",
  "Arrived at C Address",
  "Arrived at USA Address",
  "Proof Sent",
  "Other",
];

export const typeShipping = ["TBD", "Stamped", "Tracked", "EMS", "DHL", "Boat"];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros (the)",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands / Malvinas",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "North Korea ",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States Minor Outlying Islands",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

export const allGroups = [
  "2NE1",
  "3YE",
  "4Minute",
  "Aespa",
  "After School",
  "Ailee",
  "AleXa",
  "Amber",
  "AOA",
  "Apink",
  "April",
  "Baek A Yeon",
  "Baek Yerin",
  "BIBI",
  "Blackpink",
  "Blackswan",
  "BoA",
  "Bolbbalgan4",
  "Brave Girls",
  "Brown Eyed Girls",
  "Bvndit",
  "Cherry Bullet",
  "Chung Ha",
  "Cignature",
  "CL",
  "CLC",
  "Crayon Pop",
  "Dal Shabet",
  "DALsoobin",
  "DIA",
  "Dreamcatcher",
  "DreamNote",
  "Elkie",
  "Elris",
  "Everglow",
  "EXID",
  "F(x)",
  "Fanatics",
  "Fromis 9",
  "GFriend",
  "(G)I-dle",
  "Girls' Generation",
  "Gugudan",
  "GWSN",
  "HA:TFELT",
  "Heize",
  "Hello Venus",
  "Hot Issue",
  "Hyoyeon",
  "HyunA",
  "I.O.I",
  "Itzy",
  "IU",
  "Iz*One",
  "Jennie",
  "Jessi",
  "Joy",
  "Kara",
  "Kwon Eun Bi",
  "Laboum",
  "Ladies' Code",
  "Lee Hi",
  "Lightsum",
  "Lisa",
  "Loona",
  "Lovelyz",
  "Luna",
  "Lunarsolar",
  "Mamamoo",
  "Miss A",
  "Momoland",
  "Nature",
  "Natty",
  "NeonPunch",
  "Nine Muses",
  "Oh My Girl",
  "Oh!GG",
  "Orange Caramel",
  "Pristin",
  "Purple Kiss",
  "Purplebeck",
  "Red Velvet",
  "Rocket Punch",
  "S.E.S.",
  "Saturday",
  "Secret Number",
  "Sistar",
  "Sonamoo",
  "STAYC",
  "Stellar",
  "T-ara",
  "Tri.be",
  "Twice",
  "Weeekly",
  "Weki Meki",
  "Wendy",
  "WJSN",
  "Wonder Girls",
  "Woo!ah!",
  "2PM",
  "AB6IX",
  "Astro",
  "Ateez",
  "B.A.P.",
  "Baekhyun",
  "B.I",
  "Big Bang",
  "Block B",
  "The Boyz",
  "BtoB",
  "BTS",
  "CIX",
  "Cravity",
  "DAWN",
  "DEAN",
  "Enhyper",
  "Exo",
  "G-Dragon",
  "Got7",
  "H.O.T.",
  "IKon",
  "Infinite",
  "KNK",
  "Monsta X",
  "N.Flying",
  "NCT",
  "NU'EST",
  "Oneus",
  "ONF",
  "OnlyOneOf",
  "Pentagon",
  "The Rose",
  "SF9",
  "Shinee",
  "Stray Kids",
  "Suga",
  "Super Junior",
  "SuperM",
  "Taemin",
  "TXT",
  "Treasure",
  "TVXQ",
  "Victon",
  "VIXX",
  "Wanna One",
  "WayV",
  "Winner",
];

const GirlGroups = [
  "2NE1",
  "3YE",
  "4Minute",
  "Aespa",
  "After School",
  "Ailee",
  "AleXa",
  "Amber",
  "AOA",
  "Apink",
  "April",
  "Baek A Yeon",
  "Baek Yerin",
  "BIBI",
  "Blackpink",
  "Blackswan",
  "BoA",
  "Bolbbalgan4",
  "Brave Girls",
  "Brown Eyed Girls",
  "Bvndit",
  "Cherry Bullet",
  "Chung Ha",
  "Cignature",
  "CL",
  "CLC",
  "Crayon Pop",
  "Dal Shabet",
  "DALsoobin",
  "DIA",
  "Dreamcatcher",
  "DreamNote",
  "Elkie",
  "Elris",
  "Everglow",
  "EXID",
  "F(x)",
  "Fanatics",
  "Fromis 9",
  "GFriend",
  "(G)I-dle",
  "Girls' Generation",
  "Gugudan",
  "GWSN",
  "HA:TFELT",
  "Heize",
  "Hello Venus",
  "Hot Issue",
  "Hyoyeon",
  "HyunA",
  "I.O.I",
  "Itzy",
  "IU",
  "Iz*One",
  "Jennie",
  "Jessi",
  "Joy",
  "Kara",
  "Kwon Eun Bi",
  "Laboum",
  "Ladies' Code",
  "Lee Hi",
  "Lightsum",
  "Lisa",
  "Loona",
  "Lovelyz",
  "Luna",
  "Lunarsolar",
  "Mamamoo",
  "Miss A",
  "Momoland",
  "Nature",
  "Natty",
  "NeonPunch",
  "Nine Muses",
  "Oh My Girl",
  "Oh!GG",
  "Orange Caramel",
  "Pristin",
  "Purple Kiss",
  "Purplebeck",
  "Red Velvet",
  "Rocket Punch",
  "S.E.S.",
  "Saturday",
  "Secret Number",
  "Sistar",
  "Sonamoo",
  "STAYC",
  "Stellar",
  "T-ara",
  "Tri.be",
  "Twice",
  "Weeekly",
  "Weki Meki",
  "Wendy",
  "WJSN",
  "Wonder Girls",
  "Woo!ah!",
];

const BoyGroups = [
  "2PM",
  "AB6IX",
  "Astro",
  "Ateez",
  "B.A.P.",
  "Baekhyun",
  "B.I",
  "Big Bang",
  "Block B",
  "The Boyz",
  "BtoB",
  "BTS",
  "CIX",
  "Cravity",
  "DAWN",
  "DEAN",
  "Enhyper",
  "Exo",
  "G-Dragon",
  "Got7",
  "H.O.T.",
  "IKon",
  "Infinite",
  "KNK",
  "Monsta X",
  "N.Flying",
  "NCT",
  "NU'EST",
  "Oneus",
  "ONF",
  "OnlyOneOf",
  "Pentagon",
  "The Rose",
  "SF9",
  "Shinee",
  "Stray Kids",
  "Suga",
  "Super Junior",
  "SuperM",
  "Taemin",
  "TXT",
  "Treasure",
  "TVXQ",
  "Victon",
  "VIXX",
  "Wanna One",
  "WayV",
  "Winner",
];
